# Generated by Django 4.1.2 on 2023-06-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='image',
        ),
    ]
