# Generated by Django 4.1.2 on 2023-05-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescription', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdiseases',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.chronicdiseases'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.usertype'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='rating',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='rating',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient'),
        ),
        migrations.AddField(
            model_name='patientdiseases',
            name='patinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.city'),
        ),
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.ManyToManyField(through='accounts.PatientDiseases', to='prescription.chronicdiseases'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.doctor', verbose_name='Doctor_id'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.city'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('doctor', 'patient')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('doctor', 'patient')},
        ),
        migrations.AlterUniqueTogether(
            name='patientdiseases',
            unique_together={('disease', 'patinet')},
        ),
        migrations.AlterIndexTogether(
            name='patientdiseases',
            index_together={('disease', 'patinet')},
        ),
    ]
