# Generated by Django 4.1.2 on 2023-05-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_remove_screen_image_serialfilm'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('standard_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.standarddrugs')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='standard_drug',
            field=models.ManyToManyField(through='accounts.PatientDrug', to='prescription.standarddrugs'),
        ),
    ]
