# Generated by Django 4.1.2 on 2023-03-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_admin_user_ptr_alter_doctor_user_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='date_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_birth',
            field=models.DateField(),
        ),
    ]
