# Generated by Django 4.1.2 on 2023-05-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_remove_screen_image_serialfilm'),
        ('accounts', '0003_patientdrug_patient_standard_drug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientdrug',
            unique_together={('standard_drug', 'patinet')},
        ),
        migrations.AlterIndexTogether(
            name='patientdrug',
            index_together={('standard_drug', 'patinet')},
        ),
    ]
