# Generated by Django 4.1.2 on 2023-03-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_admin_date_birth_alter_doctor_date_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='date_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_birth',
            field=models.DateField(null=True),
        ),
    ]
