# Generated by Django 4.1.2 on 2023-04-06 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_admin_date_birth_alter_doctor_date_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 6)),
        ),
    ]
