# Generated by Django 4.1.2 on 2023-04-09 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 9)),
        ),
    ]
