# Generated by Django 4.1.2 on 2023-04-14 06:06

import accounts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_rating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='date_birth',
            field=models.DateField(default='2023-03-17', validators=[accounts.models.future_date_validator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_birth',
            field=models.DateField(default='2020-02-02', validators=[accounts.models.future_date_validator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_birth',
            field=models.DateField(default='2020-02-02', validators=[accounts.models.future_date_validator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 14)),
        ),
    ]
