# Generated by Django 4.1.2 on 2023-04-14 06:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_admin_date_birth_alter_doctor_date_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='date_birth',
            field=models.DateField(null=True, validators=[accounts.models.future_date_validator]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_birth',
            field=models.DateField(null=True, validators=[accounts.models.future_date_validator]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_birth',
            field=models.DateField(null=True, validators=[accounts.models.future_date_validator]),
        ),
    ]
