# Generated by Django 4.1.2 on 2023-04-14 07:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_admin_date_birth_alter_doctor_date_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='date_birth',
            field=models.DateField(default='2001-04-08', validators=[accounts.models.future_date_validator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_birth',
            field=models.DateField(default='2001-02-02', validators=[accounts.models.future_date_validator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_birth',
            field=models.DateField(default='2001-02-02', validators=[accounts.models.future_date_validator]),
            preserve_default=False,
        ),
    ]
