# Generated by Django 4.1.2 on 2023-04-18 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_admin_date_birth_alter_doctor_date_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 18)),
        ),
    ]
