# Generated by Django 4.1.2 on 2023-05-01 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_patient_booking_alter_rating_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='booking',
        ),
    ]
