# Generated by Django 4.1.2 on 2023-05-05 04:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0017_chronicdiseases'),
        ('accounts', '0015_remove_patient_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_date', models.CharField(max_length=4, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.chronicdiseases')),
                ('patinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.ManyToManyField(through='accounts.PatientDiseases', to='prescription.chronicdiseases'),
        ),
    ]
