# Generated by Django 4.1.2 on 2023-05-05 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_patientdiseases_patient_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdiseases',
            name='disease_date',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
