# Generated by Django 4.1.2 on 2023-05-11 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import prescription.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='active_Ingredient',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Ingredient name')),
                ('if_interaction_exist', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ChronicDiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clinical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_name', models.CharField(max_length=100, verbose_name='Clinical name')),
                ('clinical_location', models.CharField(max_length=255, verbose_name='Clinical location')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, validators=[prescription.models.phoneValidate])),
                ('phone', models.CharField(max_length=11, validators=[prescription.models.phoneValidate])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
            ],
            options={
                'verbose_name': 'Clinical',
                'verbose_name_plural': 'Clinicals',
            },
        ),
        migrations.CreateModel(
            name='Interaction_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_created', models.DateField(default=datetime.datetime.now)),
                ('next_consultation', models.DateField(validators=[prescription.models.future_date_validator], verbose_name='next consultation')),
                ('cancelation_date', models.DateField(null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('clinical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Clinical', to='prescription.clinical')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_id', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_id', to='accounts.patient')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
        migrations.CreateModel(
            name='StandardMedicalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Medical Analysis')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='StandardScreens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='screen name')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='StandardDrugs',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Drug name')),
                ('sideEffects', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Side Effects')),
                ('uses', models.TextField(blank=True, max_length=3000, null=True, verbose_name='uses')),
                ('warnings', models.TextField(blank=True, max_length=3000, null=True, verbose_name='warnings')),
                ('before_taking', models.TextField(blank=True, max_length=3000, null=True, verbose_name='before_taking')),
                ('how_to_take', models.TextField(blank=True, max_length=3000, null=True, verbose_name='how_to_take')),
                ('miss_dose', models.TextField(blank=True, max_length=3000, null=True, verbose_name='miss_dose')),
                ('overdose', models.TextField(blank=True, max_length=3000, null=True, verbose_name='overdose')),
                ('what_to_avoid', models.TextField(blank=True, max_length=3000, null=True, verbose_name='what_to_avoid')),
                ('activeIngredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescription.active_ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.prescription')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='StandardScreens', to='prescription.standardscreens')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.prescription')),
                ('standard_medical_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.standardmedicalanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='ingredient_interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstID', to='prescription.active_ingredient', verbose_name='First Active Ingredient ')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondID', to='prescription.active_ingredient', verbose_name='Second Active Ingredient ')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescription.interaction_status')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_in', models.DateField(default=datetime.datetime.now, verbose_name='Start in')),
                ('end_in', models.DateField(validators=[prescription.models.future_date_validator], verbose_name='End in')),
                ('consentration', models.PositiveSmallIntegerField()),
                ('dose_per_hour', models.FloatField(verbose_name='dose')),
                ('drugType', models.CharField(blank=True, max_length=100, null=True, verbose_name='Drug Type')),
                ('name_if_doesnt_exist', models.CharField(blank=True, max_length=100, null=True)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='StandardDrugs', to='prescription.standarddrugs')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[prescription.models.future_date_validator])),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('allowed_number', models.PositiveSmallIntegerField()),
                ('clinical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.clinical')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PatientBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.booking')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'unique_together': {('booking', 'patient')},
                'index_together': {('booking', 'patient')},
            },
        ),
    ]
