# Generated by Django 4.1.2 on 2023-03-22 18:19

from django.db import migrations, models
import prescription.models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='day_in_a_week',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(validators=[prescription.models.future_date_validator]),
        ),
    ]
