# Generated by Django 4.1.2 on 2023-03-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_remove_booking_day_in_a_week_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarddrugs',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Drug name'),
        ),
    ]
