# Generated by Django 4.1.2 on 2023-05-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_patientcommitment_drug_commitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcommitment',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
