# Generated by Django 4.1.2 on 2023-04-09 07:11

from django.db import migrations, models
import prescription.models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_alter_standarddrugs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical',
            name='phone',
            field=models.CharField(default='01272366419', max_length=12, validators=[prescription.models.phoneValidate]),
            preserve_default=False,
        ),
    ]
