# Generated by Django 4.1.2 on 2023-04-09 07:21

from django.db import migrations, models
import prescription.models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_alter_clinical_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical',
            name='phone',
            field=models.CharField(max_length=11, validators=[prescription.models.phoneValidate]),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='telephone',
            field=models.CharField(max_length=11, null=True, validators=[prescription.models.phoneValidate]),
        ),
    ]
