# Generated by Django 4.1.2 on 2023-05-14 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_prescription_commitment_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='Commitment_ratio',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
