# Generated by Django 4.1.2 on 2023-04-14 06:06

from django.db import migrations, models
import prescription.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_admin_date_birth_alter_doctor_date_birth_and_more'),
        ('prescription', '0005_alter_clinical_phone_alter_clinical_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[prescription.models.phoneValidate]),
        ),
        migrations.AlterUniqueTogether(
            name='patientbooking',
            unique_together={('booking', 'patient')},
        ),
        migrations.AlterIndexTogether(
            name='patientbooking',
            index_together={('booking', 'patient')},
        ),
    ]
