# Generated by Django 4.1.2 on 2023-05-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_drug_commitment_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='image',
        ),
        migrations.CreateModel(
            name='SerialFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True, null=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.screen')),
            ],
        ),
    ]
