# Generated by Django 4.1.2 on 2023-04-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_alter_clinical_telephone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarddrugs',
            name='drugType',
        ),
        migrations.AddField(
            model_name='drug',
            name='drugType',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Drug Type'),
        ),
        migrations.AddField(
            model_name='drug',
            name='name_if_doesnt_exist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='StandardDrugs', to='prescription.standarddrugs'),
        ),
        migrations.AlterField(
            model_name='ingredient_interaction',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='standarddrugs',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='standarddrugs',
            name='desease',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Desease name'),
        ),
        migrations.AlterField(
            model_name='standarddrugs',
            name='sideEffects',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Side Effects'),
        ),
    ]
