# Generated by Django 4.1.2 on 2023-05-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_remove_screen_image_serialfilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialfilm',
            name='instance_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
