# Generated by Django 4.1.2 on 2023-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0007_remove_standarddrugs_drugtype_drug_drugtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='consentration',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
