# Generated by Django 4.1.2 on 2023-04-19 19:16

from django.db import migrations, models
import django.db.models.deletion
import prescription.models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0008_drug_consentration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='end_in',
            field=models.DateField(validators=[prescription.models.future_date_validator], verbose_name='End in'),
        ),
        migrations.AlterField(
            model_name='ingredient_interaction',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescription.interaction_status'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='next_consultation',
            field=models.DateField(validators=[prescription.models.future_date_validator], verbose_name='next consultation'),
        ),
    ]
