# Generated by Django 4.1.2 on 2023-04-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0009_alter_drug_end_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_ingredient',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
