# Generated by Django 4.1.2 on 2023-04-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0010_alter_active_ingredient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarddrugs',
            name='description',
        ),
        migrations.RemoveField(
            model_name='standarddrugs',
            name='desease',
        ),
        migrations.AddField(
            model_name='standarddrugs',
            name='before_taking',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='before_taking'),
        ),
        migrations.AddField(
            model_name='standarddrugs',
            name='how_to_take',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='how_to_take'),
        ),
        migrations.AddField(
            model_name='standarddrugs',
            name='miss_dose',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='miss_dose'),
        ),
        migrations.AddField(
            model_name='standarddrugs',
            name='overdose',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='overdose'),
        ),
        migrations.AddField(
            model_name='standarddrugs',
            name='uses',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='uses'),
        ),
        migrations.AddField(
            model_name='standarddrugs',
            name='warnings',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='warnings'),
        ),
        migrations.AddField(
            model_name='standarddrugs',
            name='what_to_avoid',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='what_to_avoid'),
        ),
    ]
