# Generated by Django 4.1.2 on 2023-04-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0011_remove_standarddrugs_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_ingredient',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='standarddrugs',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='standarddrugs',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Drug name'),
        ),
    ]
