# Generated by Django 4.1.2 on 2023-04-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0012_alter_active_ingredient_id_alter_standarddrugs_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_ingredient',
            name='if_interaction_exist',
            field=models.BooleanField(default=False),
        ),
    ]
