# Generated by Django 4.1.2 on 2023-05-01 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0013_active_ingredient_if_interaction_exist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientBooking',
        ),
    ]
