# Generated by Django 4.1.2 on 2023-05-01 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_patient_booking'),
        ('prescription', '0014_delete_patientbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.booking')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'unique_together': {('booking', 'patient')},
                'index_together': {('booking', 'patient')},
            },
        ),
    ]
