# Generated by Django 4.1.2 on 2023-05-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0016_remove_screen_is_done_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicDiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=500)),
            ],
        ),
    ]
